apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplex
  template:
    metadata:
      labels:
        app: simplex
    spec:
      containers:
        - name: simplex
          image: siverteh/simplex:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "true"
